soraya/aboalisina/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import  static

urlpatterns = [

    path('admin/', admin.site.urls)   ,
    path('' , include('home.urls'))   ,
    path('', include('account.urls')) ,
    path('ckeditor/', include('ckeditor_uploader.urls')) ,
    path('blog/' , include('blog.urls' ) ) ,

]

soraya/blog/urls.py
from django.urls import path
from .views import DetailBlogView , TotalBlogsView

# Create your views here.



app_name = "blog"

urlpatterns = [
    path("total_blogs/" , TotalBlogsView.as_view() , name = "total_blog" ) ,
    path('detail_blog/<int:id>/' , DetailBlogView.as_view() , name="detail_blog" ) ,

]

soraya/home/urls.py
from django.urls import path
from .views import HomeView , AboutUserView , FAQView , ContactUsView , Error


app_name = 'home'


urlpatterns = [

    path('' , HomeView.as_view() , name = 'home' ) ,
    path('aboutus/' , AboutUserView.as_view() , name = 'aboutus' ) ,
    path('faq/' , FAQView.as_view() , name="faq" ) ,
    path('contactus/' , ContactUsView.as_view() , name='contactus' )  ,
    path('error/' , Error.as_view() , {} )
]

soraya/blog/models.py
from django.db import models
from ckeditor.fields import  RichTextField
from account.models import Profile
from django_jalali.db import models as jmodels
from account.models import Profile
from django.urls import reverse
# Create your models here.



class Category_Blog(models.Model) :
    name = models.CharField(verbose_name = 'نام دسته بندی' , max_length=100  , unique = True )
    slug = models.SlugField(verbose_name = 'آدرس دسته بندی'  )


    def __str__(self ) :
        return self.name



    class Meta :
        db_table = 'Category_Blog'
        verbose_name_plural = 'دسته بندی های وبلاگ'



class Tags_Post(models.Model) :
    name = models.CharField(verbose_name = 'نام تگ' , max_length = 100 )

    def __str__(self ) :
        return self.name

    class Meta :
        db_table = 'Tags_Post'
        verbose_name_plural  = 'تگ های پست ها'


class Post(models.Model) :

    summer_text = RichTextField(verbose_name = 'خلاصه متن' , null = True  )
    author  = models.ForeignKey(Profile , verbose_name = 'نویسنده'  ,    on_delete = models.CASCADE ,  null = True   )
    picture = models.FileField(verbose_name = 'تصویر' , upload_to = 'blog/Post/' )
    name = models.CharField(max_length   = 100 , verbose_name = 'عنوان پست' )
    slug = models.SlugField(verbose_name = 'آدرس اینترنتی' )
    category     = models.ForeignKey(Category_Blog , on_delete = models.CASCADE , related_name = 'post' , verbose_name = 'دسته بندی ' )
    description1 = RichTextField(verbose_name = 'توضیحات' , blank = True )
    description2 = RichTextField(verbose_name = 'توضیحات' , blank = True , null = True  )
    tags  = models.ManyToManyField(Tags_Post , verbose_name = 'تگ ها'  )
    times = jmodels.jDateTimeField(auto_now_add = True , verbose_name = 'زمان ایجاد'   ,  null = True )
    time_to_read = models.PositiveIntegerField(verbose_name = 'زمان  خواندن' , null = True )
    author_idea  = RichTextField(verbose_name = 'نظر نویسنده', null = True  )
    banner1      = models.FileField(verbose_name = 'بنر تبلیغاتی 1 '  , upload_to = "Post/Banner/banner1" , null = True  )
    banner2      = models.FileField(verbose_name = 'بنر تبلیغاتی 2 '  , upload_to = "Post/Banner/banner2" , null = True  )
    banner3      = models.FileField(verbose_name = 'بنر تبلیغاتی  3'  , upload_to = "Post/Banner/banner3" , null = True  )



    def __str__(self) :
        return self.name




    def get_absolute_url(self) :
        return reverse('blog:detail_blog' , args = [str(self.id)])


    class Meta :
        db_table = 'Post'
        verbose_name_plural = 'پست های وبلاگ'






class PostComment(models.Model) :

    STATUS_POST_COMMENT = (
        ('no_check' , 'بدون چک' ) ,
        ('checheck' , 'چک' ) ,
        ('pass'     , 'تایید' )
        )
    post_selected  = models.ForeignKey(Post , verbose_name = 'پست انتخاب شده'  , null = True ,on_delete = models.CASCADE  )
    name    = models.CharField(verbose_name  = 'نام پاسخ دهنده'    , max_length = 100  )
    email   = models.EmailField(verbose_name = 'ایمیل پاسخ دهنده'  )
    text    = models.TextField(verbose_name  = 'متن پاسخ'   )
    status  = models.CharField(max_length    = 20 , choices = STATUS_POST_COMMENT , default = 'no_check' , verbose_name = 'وضعیت بررسی کامنت' )
    times   = jmodels.jDateTimeField(verbose_name = '' , null = True , auto_now_add = True )
    def __str__(self) :
        return self.name

    class Meta :
        db_table = 'PostComment'
        verbose_name_plural = 'کامنت های وبلاگ'

soraya/blog/forms.py
from django import forms
from .models import PostComment



class PostCommentForm(forms.ModelForm) :

    class Meta :
        model = PostComment
        fields = ['name' , 'email' , 'text' ]

soraya/blog/views.py
from django.shortcuts import render , redirect
from .models import Post  , PostComment
from django.views import View
from .forms import PostCommentForm
from django.contrib import messages

class TotalBlogsView(View) :

    template_name = 'blog/blog-masonry.html'

    def setup(self, request , *args , **kwargs ) :
        self.total_data = Post.objects.all()
        return super().setup(request , *args , **kwargs )

    def get(self , request ) :
        return render(request , self.template_name , {'total_blogs' : self.total_data} )





class DetailBlogView(View) :

    form_comment = PostCommentForm
    template_name = 'blog/blog-detail.html'


    def setup(self , request , *args , **kwargs ) :
        self.data = Post.objects.get(id = kwargs['id'])
        self.total_comments =  PostComment.objects.filter( post_selected = self.data )
        self.another_posts  =  Post.objects.all()
        return super().setup(request , *args , **kwargs )


    def get(self , request , id ) :
        return render(request , self.template_name , {'data':self.data , 'another_posts' : self.another_posts  , 'form' : self.form_comment , 'total_comment' : self.total_comments } )


    def post(self , request , id ) :
        form = self.form_comment(request.POST )
        if form.is_valid() :
            new_comment = form.save()
            messages.success(request , 'با موفقیت نظر شما ثبت شد . بعد از  بررسی منتشر میشود' , 'success' )
            return redirect('blog:detail_blog' , id  )
        return render(request , self.template_name , {'data':self.data , 'another_posts' : self.another_posts  , 'form' : self.form_comment , 'total_comment' : self.total_comments } )

soraya/templates/blog/blog-masonry.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Eduport - LMS, Education and Course Theme</title>

	<!-- Meta Tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="author" content="Webestica.com">
	<meta name="description" content="Eduport- LMS, Education and Course Theme">

	<!-- Favicon -->
	<link rel="shortcut icon" href="assets/images/favicon.ico">

	<!-- Google Font -->
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;700&family=Roboto:wght@400;500;700&display=swap">

	<!-- Plugins CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'home/assets/vendor/font-awesome/css/all.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'home/assets/vendor/bootstrap-icons/bootstrap-icons.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'home/assets/vendor/glightbox/css/glightbox.css' %}">

	<!-- Theme CSS -->
	<link id="style-switch" rel="stylesheet" type="text/css" href="{% static 'home/assets/css/style.css' %}">

</head>

<body>

<!-- Header START -->
    {% include 'home/main_navbar.html' %}
<!-- Header END -->

<!-- **************** MAIN CONTENT START **************** -->
<main>
<!-- =======================
Page Banner START -->
<section class="py-5">
	<div class="container">
		<div class="row position-relative">
			<!-- SVG decoration -->
			<figure class="position-absolute top-0 start-0 d-none d-sm-block">
				<svg width="22px" height="22px" viewbox="0 0 22 22">
					<polygon class="fill-purple" points="22,8.3 13.7,8.3 13.7,0 8.3,0 8.3,8.3 0,8.3 0,13.7 8.3,13.7 8.3,22 13.7,22 13.7,13.7 22,13.7 "></polygon>
				</svg>
			</figure>

			<!-- Title and breadcrumb -->
			<div class="col-lg-10 mx-auto text-center position-relative">
				<!-- SVG decoration -->
				<figure class="position-absolute top-50 end-0 translate-middle-y">
					<svg width="27px" height="27px">
						<path class="fill-orange" d="M13.122,5.946 L17.679,-0.001 L17.404,7.528 L24.661,5.946 L19.683,11.533 L26.244,15.056 L18.891,16.089 L21.686,23.068 L15.400,19.062 L13.122,26.232 L10.843,19.062 L4.557,23.068 L7.352,16.089 L-0.000,15.056 L6.561,11.533 L1.582,5.946 L8.839,7.528 L8.565,-0.001 L13.122,5.946 Z"></path>
					</svg>
				</figure>

				<!-- Title -->
				<h1>Blog Masonry</h1>
				<!-- Breadcrumb -->
				<div class="d-flex justify-content-center">
					<nav aria-label="breadcrumb">
						<ol class="breadcrumb mb-0">
							<li class="breadcrumb-item"><a href="{% url 'home:home' %}">خانه</a></li>
							<li class="breadcrumb-item active" aria-current="page">وبلاگ</li>
						</ol>
					</nav>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- =======================
Page Banner END -->

<!-- =======================
Page content START -->
<section class="position-relative pt-0">
	<div class="container">
		<div class="row g-4 filter-container overflow-hidden" data-isotope='{"layoutMode": "masonry"}'>

            {% for i in total_blogs %}
			<!-- Card item START -->
			<div class="col-sm-6 col-lg-4 grid-item">
				<div class="card">
					<div class="overflow-hidden rounded-3">
						<img src="{{i.picture.url}}" class="card-img" alt="course image">
						<!-- Overlay -->
						<div class="bg-overlay bg-dark opacity-4"></div>
						<div class="card-img-overlay d-flex align-items-start p-3">
							<!-- badge -->
							<a href="#" class="badge bg-danger text-white">{{i.category}}</a>
						</div>
					</div>

					<!-- Card body -->
					<div class="card-body px-3">
						<!-- Title -->
						<h5 class="card-title"><a href="{{i.get_absolute_url}}">{{i.name}}</a></h5>
						<p class="text-truncate-2">Affronting imprudence do he he everything. Offered chiefly farther of my no colonel shyness. Such on help ye some door if in. Laughter proposal laughing any son law consider. Needed except up piqued an.  </p>
						<!-- Info -->
						<div class="d-flex justify-content-between">
							<h6 class="mb-0"><a href="#">Frances Guerrero</a></h6>
							<span class="small">30M Ago</span>
						</div>
					</div>
				</div>
			</div>
			<!-- Card item END -->
			{% endfor %}



		</div> <!-- Row end -->

		<!-- Load more button START -->
		<div class="text-center mt-4">
			<a href="#" class="btn btn-primary-soft mb-0">بیشتر<i class="fas fa-sync ms-2"></i></a>
		</div>
		<!-- Load more button END -->
	</div>
</section>
<!-- =======================
Page content END -->

</main>
<!-- **************** MAIN CONTENT END **************** -->

<!-- =======================
Footer START -->
    {% include 'blog/footer_share_blog.html' %}
<!-- =======================
Footer END -->

<!-- Back to top -->
<div class="back-top"><i class="bi bi-arrow-up-short position-absolute top-50 start-50 translate-middle"></i></div>

<!-- Bootstrap JS -->
<script src="{% static 'home/assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>

<!-- Vendors -->
<script src="{% static 'home/assets/vendor/isotope/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'home/assets/vendor/imagesLoaded/imagesloaded.js' %}"></script>

<!-- Template Functions -->
<script src="{% static 'home/assets/js/functions.js' %}"></script>

</body>
</html>

soraya/templates/blog/footer_share_blog.html
{% load static %}
<footer class="pt-5 bg-light">
	<div class="container">
		<!-- Row START -->
		<div class="row g-4">

			<!-- Widget 1 START -->
			<div class="col-lg-3">
				<!-- logo -->
				<a class="me-0" href="index.html">
					<img class="light-mode-item h-40px" src="{%  static 'home/assets/images/logo.jpg' %}" alt="logo">
					<img class="dark-mode-item h-40px" src="{%  static 'home/assets/images/logo.jpg' %}" alt="logo">
				</a>
				<p class="my-3">Eduport education theme, built specifically for the education centers which is dedicated to teaching and involve learners. </p>
				<!-- Social media icon -->
				<ul class="list-inline mb-0 mt-3">
					<li class="list-inline-item"> <a class="btn btn-white btn-sm shadow px-2 text-facebook" href="#"><i class="fab fa-fw fa-facebook-f"></i></a> </li>
					<li class="list-inline-item"> <a class="btn btn-white btn-sm shadow px-2 text-instagram" href="#"><i class="fab fa-fw fa-instagram"></i></a> </li>
					<li class="list-inline-item"> <a class="btn btn-white btn-sm shadow px-2 text-twitter" href="#"><i class="fab fa-fw fa-twitter"></i></a> </li>
					<li class="list-inline-item"> <a class="btn btn-white btn-sm shadow px-2 text-linkedin" href="#"><i class="fab fa-fw fa-linkedin-in"></i></a> </li>
				</ul>
			</div>
			<!-- Widget 1 END -->

			<!-- Widget 2 START -->
			<div class="col-lg-6">
				<div class="row g-4">
					<!-- Link block -->
					<div class="col-6 col-md-4">
						<h5 class="mb-2 mb-md-4">Company</h5>
						<ul class="nav flex-column">
							<li class="nav-item"><a class="nav-link" href="#">About us</a></li>
							<li class="nav-item"><a class="nav-link" href="#">Contact us</a></li>
							<li class="nav-item"><a class="nav-link" href="#">News and Blogs</a></li>
							<li class="nav-item"><a class="nav-link" href="#">Library</a></li>
							<li class="nav-item"><a class="nav-link" href="#">Career</a></li>
						</ul>
					</div>

					<!-- Link block -->
					<div class="col-6 col-md-4">
						<h5 class="mb-2 mb-md-4">Community</h5>
						<ul class="nav flex-column">
							<li class="nav-item"><a class="nav-link" href="#">Documentation</a></li>
							<li class="nav-item"><a class="nav-link" href="{% url 'home:faq' %}">سوالات پر تکرار </a></li>
							<li class="nav-item"><a class="nav-link" href="#">Forum</a></li>
							<li class="nav-item"><a class="nav-link" href="#">Sitemap</a></li>
						</ul>
					</div>

					<!-- Link block -->
					<div class="col-6 col-md-4">
						<h5 class="mb-2 mb-md-4">Teaching</h5>
						<ul class="nav flex-column">
							<li class="nav-item"><a class="nav-link" href="#">Become a teacher</a></li>
							<li class="nav-item"><a class="nav-link" href="#">How to guide</a></li>
							<li class="nav-item"><a class="nav-link" href="#">Terms &amp; Conditions</a></li>
						</ul>
					</div>
				</div>
			</div>
			<!-- Widget 2 END -->

			<!-- Widget 3 START -->
			<div class="col-lg-3">
				<h5 class="mb-2 mb-md-4">Contact</h5>
				<!-- Time -->
				<p class="mb-2">
					Toll free:<span class="h6 fw-light ms-2">+1234 568 963</span>
					<span class="d-block small">(9:AM to 8:PM IST)</span>
				</p>

				<p class="mb-0">Email:<span class="h6 fw-light ms-2">example@gmail.com</span></p>

				<div class="row g-2 mt-2">
					<!-- Google play store button -->
					<div class="col-6 col-sm-4 col-md-3 col-lg-6">
						<a href="#"> <img src="{% static 'home/assets/images/client/google-play.svg' %}" alt=""> </a>
					</div>
					<!-- App store button -->
					<div class="col-6 col-sm-4 col-md-3 col-lg-6">
						<a href="#"> <img src="{% static 'home/assets/images/client/app-store.svg' %}" alt="app-store"> </a>
					</div>
				</div> <!-- Row END -->
			</div>
			<!-- Widget 3 END -->
		</div><!-- Row END -->

		<!-- Divider -->
		<hr class="mt-4 mb-0">

		<!-- Bottom footer -->
		<div class="py-3">
			<div class="container px-0">
				<div class="d-md-flex justify-content-between align-items-center py-3 text-center text-md-left">
					<!-- copyright text -->
					<div class="text-primary-hover"> Copyrights <a href="#" class="text-body">©2021 Eduport</a>. All rights reserved. </div>
					<!-- copyright links-->
					<div class=" mt-3 mt-md-0">
						<ul class="list-inline mb-0">
							<li class="list-inline-item">
								<!-- Language selector -->
								<div class="dropup mt-0 text-center text-sm-end">
									<a class="dropdown-toggle nav-link" href="#" role="button" id="languageSwitcher" data-bs-toggle="dropdown" aria-expanded="false">
										<i class="fas fa-globe me-2"></i>Language
									</a>
									<ul class="dropdown-menu min-w-auto" aria-labelledby="languageSwitcher">
										<li><a class="dropdown-item me-4" href="#"><img class="fa-fw me-2" src="{% static 'home/assets/images/flags/uk.svg' %}" alt="">English</a></li>
										<li><a class="dropdown-item me-4" href="#"><img class="fa-fw me-2" src="{% static 'home/assets/images/flags/gr.svg' %}" alt="">German </a></li>
										<li><a class="dropdown-item me-4" href="#"><img class="fa-fw me-2" src="{% static 'home/assets/images/flags/sp.svg' %}" alt="">French</a></li>
									</ul>
								</div>
							</li>
							<li class="list-inline-item"><a class="nav-link" href="#">Terms of use</a></li>
							<li class="list-inline-item"><a class="nav-link pe-0" href="#">Privacy policy</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</footer>