soraya/aboalisina/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import  static

urlpatterns = [

    path('admin/', admin.site.urls)   ,
    path('' , include('home.urls'))   ,
    path('', include('account.urls')) ,
    path('ckeditor/', include('ckeditor_uploader.urls')) ,
    path('blog/' , include('blog.urls' ) ) ,

]

soraya/account/urls.py
from django.urls import path
from .views import LoginView , LogoutView , SignUpView

app_name = 'account'
urlpatterns = [
    path('login/'  , LoginView.as_view(), name='login'     ) ,
    path('logout/' , LogoutView.as_view() , name='logout' ) ,
    path('signup/' , SignUpView.as_view(), name='signup'  ) ,
]

soraya/blog/urls.py
from django.urls import path
from .views import DetailBlogView , TotalBlogsView

# Create your views here.



app_name = "blog"

urlpatterns = [
    path("total_blogs/" , TotalBlogsView.as_view() , name = "total_blog" ) ,
    path('detail_blog/<int:id>/' , DetailBlogView.as_view() , name="detail_blog" ) ,

]

soraya/home/urls.py
from django.urls import path
from .views import HomeView , AboutUserView , FAQView , ContactUsView , Error


app_name = 'home'


urlpatterns = [

    path('' , HomeView.as_view() , name = 'home' ) ,
    path('aboutus/' , AboutUserView.as_view() , name = 'aboutus' ) ,
    path('faq/' , FAQView.as_view() , name="faq" ) ,
    path('contactus/' , ContactUsView.as_view() , name='contactus' )  ,
    path('error/' , Error.as_view() , {} )
]

soraya/home/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.



class MainSlider(models.Model) :
    name = models.CharField(verbose_name = "نام تصویر" , max_length = 100 )
    picture = models.FileField(verbose_name = 'تصویر'  , upload_to = 'MainSlider/' )

    def __str__(self) :
        return self.name


    class Meta :
        db_table = 'MainSlider'
        verbose_name_plural = 'تصاویر اسلایدر ابتدایی'


class AboutUs(models.Model) :
    title = models.CharField(max_length=100 , verbose_name='درباره ما' )
    picture = models.FileField(upload_to='AboutUs/', verbose_name='تصویر درباره ما' )
    text1 = RichTextField(verbose_name= 'توضیحات 1' , null = True, blank = True )
    text2 = RichTextField(verbose_name='توضیحات 2' , null=True, blank=True )
    text3 = RichTextField(verbose_name='توضیحات 3 ' , null = True , blank=True )

    def __str__(self):
        return self.title


    class Meta :
        db_table = 'AboutUs'
        verbose_name_plural='درباره ما'
        ####

class FAQ(models.Model) :
    title = models.CharField(max_length=100 , verbose_name='عنوان سوال')
    text  = RichTextField(verbose_name='متن' )


    def __str__(self):
        return self.title


    class Meta :
        db_table = 'FAQ'
        verbose_name_plural='سوالات پر تکرار '




class ContactUs(models.Model) :

    STATUS_CHOICES = (
        ('pre' , 'بدون بررسی' ) , ('now' ,'در حال بررسی' ) , ('end' , 'تمام شده')
        )

    name   = models.CharField(verbose_name  = "نام" , max_length = 100 )
    family = models.CharField(verbose_name  = "نام خانوادگی" , max_length = 100 )
    email  = models.EmailField(verbose_name = "ایمیل"  )
    phone  = models.CharField(verbose_name  = 'شماره تلفن' , max_length = 11  , null = True )
    text   = models.TextField(verbose_name  = "متن"  )
    status = models.CharField(max_length = 20 , choices = STATUS_CHOICES ,default = 'pre' )

    def __str__(self ) :
        return f'{self.name} - {self.family} '


    class Meta :
        db_table = "ContactUs"
        verbose_name_plural = 'ارتباط با ما'


class Supporter(models.Model) :

    name    = models.CharField(verbose_name = 'نام حامی ما' , max_length = 100 )
    picture = models.FileField(verbose_name = 'لوگو' , upload_to = 'Supporter/' )


    def __str__(self ) :
        return self.name



    class Meta :
        db_table = 'Supporter'
        verbose_name_plural = 'Supporter'

soraya/home/forms.py
from django import forms
from .models import ContactUs



class ContactUsForms(forms.ModelForm) :

    class Meta :
        model  = ContactUs
        fields = ['name' , 'family' , 'email' , 'phone'  , 'text' ]

soraya/home/views.py
from django.shortcuts import render ,redirect
from django.views import View
from .models import AboutUs , FAQ , ContactUs , Supporter , MainSlider
from blog.models import Post
from .forms import ContactUsForms
from django.contrib import messages

# Create your views here.


class HomeView(View) :

    template_name = 'home/index-2.html'


    def setup(self , request , *args , **kwargs ) :
        self.supporter = Supporter.objects.all()
        self.blogs     = Post.objects.all()
        self.picture_slider = MainSlider.objects.first()
        return super().setup(request , *args , **kwargs )

    def get(self , request ) :
        return render(request , self.template_name , {'supporter' : self.supporter , 'picture_slider' : self.picture_slider , 'blogs' : self.blogs })

    def post(self , request ):
        return render(request , self.template_name , {'supporter' : self.supporter , 'picture_slider' : self.picture_slider  , 'blogs' : self.blogs })


class AboutUserView(View) :

    template_name = 'account/about-us.html'


    def setup(self , request , *args , **kwargs ) :
        self.data = AboutUs.objects.first()
        return super().setup(request , *args , **kwargs )

    def get(self , request ) :
        return render(request , self.template_name , {'data' : self.data } )


class FAQView(View) :

    template_name = 'account/faq.html'

    def setup(self , request , *args , **kwargs ) :
        self.data = FAQ.objects.all()
        return super().setup(request , *args , **kwargs )

    def get(self , request ) :
        return render(request , self.template_name , {'data':self.data } )


class ContactUsView(View) :


    contact_form  = ContactUsForms
    template_name = 'home/contact-us.html'


    def get(self , request ) :
        return render(request , self.template_name , {'form' : self.contact_form} )



    def post(self, request ) :
        form = self.contact_form(request.POST )
        if form.is_valid() :
            new_contact = form.save()
            messages.success(request , 'با موفقیت پیام شما ثبت شد' , 'success')
            return redirect('home:home')

        return render(request , self.template_name , {'form' : self.contact_form } )



class Error(View) :

    template_name = 'home/error-404.html'


    def get(self , request ) :
        return render(request , self.template_name , {} )

soraya/templates/home/cookies.html
{% load static %}
<div class="alert alert-light fade show position-fixed start-0 bottom-0 z-index-99 rounded-3 shadow p-4 ms-3 mb-3 col-10 col-md-4 col-lg-3 col-xxl-2" role="alert">
	<div class="text-dark text-center">
		<!-- Image -->
		<img src="{%  static 'home/assets/images/logo.jpg' %}" class="h-50px mb-3" alt="cookie">
		<!-- Content -->
		<p class="mb-0">
			این وب سایت کوکی ها را در رایانه شما ذخیره می کند. برای کسب اطلاعات بیشتر در مورد کوکی هایی که استفاده می کنیم، به شرایط سایت مراجعه کنید.


			<a class="text-dark" href="#"><u> </u></a></p>
		<!-- Buttons -->
		<div class="mt-3">
			<button type="button" class="btn btn-success-soft btn-sm mb-0" data-bs-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">پذیرش</span>
			</button>
			<button type="button" class="btn btn-danger-soft btn-sm mb-0" data-bs-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">رد</span>
			</button>
		</div>
	</div>
</div>

soraya/templates/home/footer.html
{% load static %}
<footer class="footer -type-4 bg-dark-2">
        <div class="container">
          <div class="row y-gap-30 justify-between pt-60">
            <div class="col-lg-7 col-md-6">
              <div class="text-17 fw-500 text-white uppercase mb-25">
                در تماس باشید
              </div>
              <form action="#" class="form-single-field -base mt-15">
                <input class="py-20 px-30 bg-dark-6 rounded-200 text-white" type="text" placeholder="ایمیل شما...">
                <button class="button -white rounded-full" type="submit">
                  <i class="icon-arrow-left text-24 text-dark-1"></i>
                </button>
              </form>
            </div>

            <div class="col-xl-4 col-lg-5 col-md-6">
              <div class="footer-header__logo">
                <img style="width:100px;heigth:100px" src="{% static 'home/img/footer/footer-logo.jpg' %}" alt="logo">
              </div>

              <div class="d-flex justify-between mt-30">
                <div class="">
                  <div class="text-white opac-70">پاسخگویی رایگان به مشتری</div>
                  <div class="text-16 lh-1 fw-500 text-white mt-5">09390000000</div>
                </div>
                <div class="">
                  <div class="text-white opac-70">به پشتیبانی احتیاج دارید؟</div>
                  <div class="text-16 lh-1 fw-500 text-white mt-5">hi@educrat.com</div>
                </div>
              </div>
            </div>
          </div>

          <div class="row y-gap-30 justify-between pt-60 pb-60">
            <div class="col-lg-7 col-md-6">
              <div class="row y-gap-30">
                <div class="col-lg-4 col-md-4">
                  <div class="text-17 fw-500 text-white uppercase mb-25">درباره ما</div>
					<div class="d-flex y-gap-10 flex-column text-white">
					  <a href="about-1.html">درباره ما</a>
					  <a href="blog-list-1.html">لیست وبلاگ</a>
					  <a href="instructor-become.html">مدرس شوید</a>
					  <a href="blog-list-1.html">لیست وبلاگ</a>
					  <a href="#">بازگشت وجه</a>
					  <a href="contact-1.html">تماس با ما</a>
					</div>
                </div>

                <div class="col-lg-8 col-md-8">
                  <div class="text-17 fw-500 text-white uppercase mb-25">دسته بندی ها</div>
                <div class="row justify-between y-gap-20">
                  <div class="col-md-6">
                    <div class="d-flex y-gap-10 flex-column text-white">
                      <a href="courses-single-1.html">برنامه نویسی</a>
                      <a href="courses-single-2.html">طراحی وب</a>
                      <a href="courses-single-3.html">مالی و حسابداری</a>
                      <a href="courses-single-4.html">فناوری اطلاعات</a>
                      <a href="courses-single-5.html">هوش مصنوعی</a>
                      <a href="courses-single-6.html">رباتیک</a>
                      <a href="courses-single-1.html">بازاریابی</a>
                    </div>
                  </div>

                  <div class="col-md-6">
                    <div class="d-flex y-gap-10 flex-column text-white">
                      <a href="courses-single-1.html">مدیریت پروژه</a>
                      <a href="courses-single-2.html">طراحی گرافیک</a>
                      <a href="courses-single-3.html">نرم افزار</a>
                      <a href="courses-single-4.html">عکاسی</a>
                      <a href="courses-single-5.html">بانک های اطلاعاتی</a>
                      <a href="courses-single-6.html">بهینه سازی وب</a>
                    </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div class="col-xl-4 col-lg-5 col-md-6">
              <div class="">
                <div class="text-17 uppercase text-white fw-500">آموخته های خود را ارتقا دهید</div>

                <div class="d-flex mt-15">
                  <div class="d-flex items-center rounded-8 px-25 py-10 footer-bg-color">
                    <div class="icon-apple text-white text-24"></div>
                    <div class="text-white mr-20">
                      <div class="text-13 lh-12">دانلود از</div>
                      <div class="text-15 fw-500 lh-12 mt-3">Apple Store</div>
                    </div>
                  </div>

                  <div class="d-flex items-center rounded-8 px-25 py-10 footer-bg-color mr-10">
                    <div class="icon-play-market text-white text-24"></div>
                    <div class="text-white mr-20">
                   <div class="text-13 lh-12">دریافت از</div>
                      <div class="text-15 fw-500 lh-12 mt-3">Google Play</div>
                    </div>
                  </div>
                </div>
              </div>

              <div class="footer-header-socials mt-60">
                <div class="text-17 uppercase text-white fw-500"></div>
                <div class="footer-header-socials__list d-flex items-center mt-15">
                  <a href="#" class="size-40 d-flex justify-center items-center text-white"><i class="icon-facebook"></i></a>
                  <a href="#" class="size-40 d-flex justify-center items-center text-white"><i class="icon-twitter"></i></a>
                  <a href="#" class="size-40 d-flex justify-center items-center text-white"><i class="icon-instagram"></i></a>
                  <a href="#" class="size-40 d-flex justify-center items-center text-white"><i class="icon-linkedin"></i></a>
                </div>
              </div>
            </div>
          </div>

          <div class="py-30 border-top-light-15">
            <div class="row justify-between items-center y-gap-20">
              <div class="col-auto">
                <div class="d-flex items-center h-100 text-white">
                  © 2022 کلیه حقوق این قالب متعلق به گروه توسعه پردازان می باشد.
                </div>
              </div>

              <div class="col-auto">
                <div class="d-flex x-gap-20 y-gap-20 items-center flex-wrap">
                  <div>
                    <div class="d-flex x-gap-15 text-white">
                      <a href="help-center.html">پشتیبانی</a>
                      <a href="terms.html">شرایط</a>
                      <a href="terms.html">امنیت</a>
                      <a href="terms.html">حریم خصوصی</a>
                      <a href="terms.html">ضوابط</a>
                    </div>
                  </div>

                  <div>
                    <a href="#" class="button px-30 h-50 -dark-6 rounded-200 text-white">
                      <i class="icon-worldwide text-20 ml-15"></i><span class="text-15">فارسی</span>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </footer>

soraya/templates/home/home_footer.html
{% load static %}
<footer class="pt-0 bg-blue rounded-4 position-relative mx-2 mx-md-4 mb-3">
	<!-- SVG decoration for curve -->
	<figure class="mb-0">
		<svg class="fill-body rotate-180" width="100%" height="150" viewbox="0 0 500 150" preserveaspectratio="none">
			<path d="M0,150 L0,40 Q250,150 500,40 L580,150 Z"></path>
		</svg>
	</figure>

	<div class="container">
		<div class="row mx-auto">
			<div class="col-lg-6 mx-auto text-center my-5">
				<!-- Logo -->
				<img class="mx-auto h-40px" src="{%  static 'home/assets/images/logo.jpg' %}" alt="logo">
				<p class="mt-3 text-white">مدرسه آنلاین و هوشمند بوعلی سینا </p>
				<!-- Links -->
        <ul class="nav justify-content-center text-primary-hover mt-3 mt-md-0">
          <li class="nav-item"><a class="nav-link text-white" href="{% url 'home:aboutus' %}">درباره ما </a></li>

          <li class="nav-item"><a class="nav-link text-white" href="{% url 'home:contactus' %}"> ارتباط با ما</a></li>

        </ul>
				<!-- Social media button -->
				<ul class="list-inline mt-3 mb-0">
					<li class="list-inline-item">
						<a class="btn btn-white btn-sm shadow px-2 text-facebook" href="#">
							<i class="fab fa-fw fa-facebook-f"></i>
						</a>
					</li>
					<li class="list-inline-item">
						<a class="btn btn-white btn-sm shadow px-2 text-instagram" href="#">
							<i class="fab fa-fw fa-instagram"></i>
						</a>
					</li>
					<li class="list-inline-item">
						<a class="btn btn-white btn-sm shadow px-2 text-twitter" href="#">
							<i class="fab fa-fw fa-twitter"></i>
						</a>
					</li>
					<li class="list-inline-item">
						<a class="btn btn-white btn-sm shadow px-2 text-linkedin" href="#">
							<i class="fab fa-fw fa-linkedin-in"></i>
						</a>
					</li>
				</ul>
				<!-- Bottom footer link -->
				<div class="mt-3 text-white">©2021 <a href="" class="text-reset btn-link text-primary-hover" target="_blank">  نمامی حقوق محفوظ میباشد </div>
			</div>
		</div>
	</div>
</footer>

soraya/templates/home/home_footer2.html
{% load static %}
{% include 'account/nav_mobile_footer.html' %}

soraya/templates/home/main_navbar.html
{% load static %}
<header class="navbar-light header-static navbar-sticky">
	<!-- Logo Nav START -->
	<nav class="navbar navbar-expand-xl">
		<div class="container">
			<!-- Logo START -->
			<a class="navbar-brand me-0" href="{% url 'home:home' %}">
				<img class="light-mode-item navbar-brand-item" src="{%  static 'home/assets/images/logo.jpg' %}" alt="logo">
				<img class="dark-mode-item navbar-brand-item" src="{%  static 'home/assets/images/logo.jpg' %}" alt="logo">
			</a>
			<!-- Logo END -->

			<!-- Responsive navbar toggler -->
      <button class="navbar-toggler ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-animation">
					<span></span>
					<span></span>
					<span></span>
				</span>
			</button>

			<!-- Main navbar START -->
			<div class="navbar-collapse collapse" id="navbarCollapse">

				<!-- Nav Search END -->
				<ul class="navbar-nav navbar-nav-scroll mx-auto">
					<!-- Nav item 1 Demos -->
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle active" href="#" id="demoMenu" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">خانه</a>
						<ul class="dropdown-menu" aria-labelledby="demoMenu">

							<li> <a class="dropdown-item active" href="{% url 'home:home' %}">خانه</a></li>

							<li> <hr class="dropdown-divider"></li>

						</ul>
					</li>

					<!-- Nav item 2 Pages -->
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="pagesMenu" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">دسترسی ها</a>
						<ul class="dropdown-menu" aria-labelledby="pagesMenu">
							<!-- Dropdown submenu -->
							<li class="dropdown-submenu dropend">
								<a class="dropdown-item dropdown-toggle" href="#">دوره ها </a>
								<ul class="dropdown-menu dropdown-menu-start" data-bs-popper="none">
									<li> <a class="dropdown-item" href="">Course Grid Classic</a></li>
								</ul>
							</li>

							<!-- Dropdown submenu -->
							<li class="dropdown-submenu dropend">
								<a class="dropdown-item dropdown-toggle" href="#">درباره ما </a>
								<ul class="dropdown-menu dropdown-menu-start" data-bs-popper="none">
									<li> <a class="dropdown-item" href="{% url 'home:aboutus' %}">درباره ما</a></li>

								</ul>
							</li>



							<!-- Dropdown submenu -->
							<li class="dropdown-submenu dropend">
								<a class="dropdown-item dropdown-toggle" href="#">احراز هویت </a>
								<ul class="dropdown-menu dropdown-menu-start" data-bs-popper="none">
								    {% if user.is_authenticated %}
								        <li> <a class="dropdown-item" href="{% url 'account:logout' %}">خروج</a></li>
								    {% else %}
									    <li> <a class="dropdown-item" href="{% url 'account:login' %}">ورود</a></li>
									    <li> <a class="dropdown-item" href="{% url 'account:signup' %}">ثبت نام </a></li>
									    <li> <a class="dropdown-item" href="">فراموشی رمز </a></li>

									{% endif %}
								</ul>
							</li>

							<li> <a class="dropdown-item" href="{% url 'home:faq' %}">سوالات پر تکرار</a></li>

						</ul>
					</li>

					<!-- Nav item 3 Account -->
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="accounntMenu" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">حساب کاربری</a>
						<ul class="dropdown-menu" aria-labelledby="accounntMenu">
							<!-- Dropdown submenu -->
							<li class="dropdown-submenu dropend">
								<a class="dropdown-item dropdown-toggle" href="#"><i class="fas fa-user-tie fa-fw me-1"></i>کارمندان</a>
								<ul class="dropdown-menu dropdown-menu-start" data-bs-popper="none">
									<li> <a class="dropdown-item" href=""><i class="bi bi-grid-fill fa-fw me-1"></i>معلمین</a> </li>

								</ul>
							</li>

							<!-- Dropdown submenu -->
								<li class="dropdown-submenu dropend">
								<a class="dropdown-item dropdown-toggle" href="#"><i class="fas fa-user-graduate fa-fw me-1"></i>دانش آموز</a>
								<ul class="dropdown-menu dropdown-menu-start" data-bs-popper="none">
									<li> <a class="dropdown-item" href="student-dashboard.html"><i class="bi bi-grid-fill fa-fw me-1"></i>داشبورد</a> </li>


								</ul>
							</li>
                            {% if user.is_authenticated %}

							<li> <hr class="dropdown-divider"></li>
							<li> <a class="dropdown-item" href="instructor-edit-profile.html"><i class="fas fa-fw fa-edit me-1"></i> ویرایش پروفایل </a> </li>
							<li> <a class="dropdown-item" href="instructor-setting.html"><i class="fas fa-fw fa-cog me-1"></i>تنظیمات</a> </li>
							{% endif%}
						</ul>
					</li>

					<!-- Nav item 4 Component-->


					<!-- Nav item 5 link-->
					<li class="nav-item dropdown">
						<a class="nav-link" href="#" id="advanceMenu" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							<i class="fas fa-ellipsis-h"></i>
						</a>
						<ul class="dropdown-menu dropdown-menu-end min-w-auto" data-bs-popper="none">
							<li>
								<a class="dropdown-item" href="" target="_blank">
									<i class="text-warning fa-fw bi bi-life-preserver me-2"></i>پشتیبانی
								</a>
							</li>

							<li> <hr class="dropdown-divider"></li>


						</ul>
					</li>
				</ul>
			</div>
			<!-- Main navbar END -->

			<!-- Nav Search START -->
			<div class="nav-item dropdown nav-search px-1 px-lg-3">
				<a class="nav-link" role="button" href="#" id="navSearch" data-bs-toggle="dropdown" aria-expanded="true" data-bs-auto-close="outside" data-bs-display="static">
					<i class="bi bi-search fs-4"> </i>
				</a>
				<div class="dropdown-menu dropdown-menu-end shadow rounded p-2" aria-labelledby="navSearch" data-bs-popper="none">
					<form class="input-group">
						<input class="form-control border-primary" type="search" placeholder="جستجو" aria-label="Search">
						<button class="btn btn-primary m-0" type="submit">جستجو</button>
					</form>

					<!-- Recent search -->
					<ul class="list-group list-group-borderless p-2 small">
						<li class="list-group-item d-flex justify-content-between align-items-center">
							<span class="fw-bold">جستجو های اخیر </span>
							<button class="btn btn-sm btn-link mb-0 px-0">پاک کردن </button>
						</li>
						<li class="list-group-item text-primary-hover text-truncate">
							<a href="#" class="text-body"> <i class="far fa-clock me-1"></i> آموزش زبان فارسی </a>
						</li>

					</ul>
				</div>
			</div>
			<!-- Nav Search END -->

      <!-- Profile START -->
			<div class="dropdown ms-1 ms-lg-0">
				<a class="avatar avatar-sm p-0" href="#" id="profileDropdown" role="button" data-bs-auto-close="outside" data-bs-display="static" data-bs-toggle="dropdown" aria-expanded="false">
					<img class="avatar-img rounded-circle" src="{%  static 'home/assets/images/logo.jpg' %}" alt="avatar">
				</a>
				<ul class="dropdown-menu dropdown-animation dropdown-menu-end shadow pt-3" aria-labelledby="profileDropdown">
					<!-- Profile info -->
					<li class="px-3">
						<div class="d-flex align-items-center">
							<!-- Avatar -->
							{% if user.is_authenticated  %}

							    {% if user.profile.picture.url  %}
        							<div class="avatar me-3">
        								<img class="avatar-img rounded-circle shadow" src="{{user.profile.picture.url}}" alt="avatar">
        							</div>
							    {% else %}
        							<div class="avatar me-3">
        								<img class="avatar-img rounded-circle shadow" src="{%  static 'home/assets/images/logo.jpg' %}" alt="avatar">
        							</div>

							    {% endif %}

							{% else %}
        							<div class="avatar me-3">
        								<img class="avatar-img rounded-circle shadow" src="{%  static 'home/assets/images/logo.jpg' %}" alt="avatar">
        							</div>

							{% endif %}
							<div>
							    {% if user.is_authenticated  %}
								<a class="h6" href="#">{{user.email}}</a>
								{% else %}
								<a class="h6" href="#">هنوز وارد نشدید</a>
								{% endif %}
							</div>
						</div>
						<hr>
					</li>
					<!-- Links -->

					<li><a class="dropdown-item" href="#"><i class="bi bi-info-circle fa-fw me-2"></i> پشتیبانی </a></li>
                    {% if user.is_authenticated %}

					<li><a class="dropdown-item" href="#"><i class="bi bi-person fa-fw me-2"></i> ویرایش پروفایل </a></li>
					<li><a class="dropdown-item" href="#"><i class="bi bi-gear fa-fw me-2"></i> تنظیمات حساب کاربری  </a></li>
					<li><a class="dropdown-item bg-danger-soft-hover" href="{% url 'account:logout' %}"><i class="bi bi-power fa-fw me-2"></i>خروج</a></li>
					{% endif %}
					<li> <hr class="dropdown-divider"></li>
					<!-- Dark mode switch START -->
					<li>
						<div class="modeswitch-wrap" id="darkModeSwitch">
							<div class="modeswitch-item">
								<div class="modeswitch-icon"></div>
							</div>
							<span>Dark mode</span>
						</div>
					</li>
          <!-- Dark mode switch END -->
				</ul>
			</div>
			<!-- Profile START -->
		</div>
	</nav>
	<!-- Logo Nav END -->
</header>